//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Own
    {
        public int RouteID { get; set; }
        public string AirlineIATA { get; set; }
    
        public virtual Airline Airline { get; set; }
    }
}
